# Generated by Django 4.1.1 on 2022-12-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0002_remove_karyawanmodels_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyawanmodels',
            name='img',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
