# Generated by Django 4.1.1 on 2022-12-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0003_karyawanmodels_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawanmodels',
            name='img',
            field=models.ImageField(null=True, upload_to='static/img'),
        ),
    ]
