# Generated by Django 4.1.1 on 2022-12-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0005_rename_nama_karyawanmodels_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawanmodels',
            name='umur',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
