# Generated by Django 4.1.1 on 2022-12-15 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0006_alter_karyawanmodels_umur'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='karyawanmodels',
            options={'permissions': (('Admin', 'Can change karyawan'), ('Karyawan', 'Only Profile'))},
        ),
    ]
