# Generated by Django 4.1.1 on 2022-12-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0007_alter_karyawanmodels_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyawanmodels',
            name='alamat',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='karyawanmodels',
            name='telepon',
            field=models.IntegerField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='karyawanmodels',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
