# Generated by Django 4.1.1 on 2022-12-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karyawan', '0008_karyawanmodels_alamat_karyawanmodels_telepon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawanmodels',
            name='telepon',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
